#!/usr/bin/env bash
set -euo pipefail

VERSION_MAJOR=2
VERSION_MINOR=0
VERSION_PATCH=0

BUILD_TIMESTAMP="$(date +%Y%m%d%H%M)"
AQUANTA_VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}-${BUILD_TIMESTAMP}"

export VERSION_MAJOR VERSION_MINOR VERSION_PATCH BUILD_TIMESTAMP AQUANTA_VERSION
